### ISSUE TITLE
undefined reference to symbol 'inflate'

### ISSUE THREAD

**Issue by kowalcj0** [arybczak/ncmpcpp#138]
Hi,

I can't compile the latest version on ncmpcpp on rpi 3 running `Ubuntu Mate 16.04 LTS kernel 4.4.11-v7+`

``` bash
$ ./configure --with-curl --with-fftw --with-taglib --enable-outputs --enable-visualizer --enable-clock --enable-unicode

$ make
make  all-recursive
make[1]: Entering directory '/home/rpi/git/ncmpcpp'
Making all in src
make[2]: Entering directory '/home/rpi/git/ncmpcpp/src'
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++0x   -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/lib/arm-linux-gnueabihf -lcurl -L/usr/local/lib -ltag
libtool: link: g++ -g -O2 -std=c++0x -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/lib/arm-linux-gnueabihf /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so -L/usr/local/lib -ltag -pthread
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so: undefined reference to symbol 'inflate'
//lib/arm-linux-gnueabihf/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:534: recipe for target 'ncmpcpp' failed
make[2]: *** [ncmpcpp] Error 1
make[2]: Leaving directory '/home/rpi/git/ncmpcpp/src'
Makefile:467: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rpi/git/ncmpcpp'
Makefile:378: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by siccegge** [comment]
Looks like a bug in your libcurl

`/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so: undefined reference to symbol 'inflate'`

**Comment by kowalcj0** [comment]
hmmm...


it's the latest available version for the ARM cpus

```
$ dpkg -s libcurl4-gnutls-dev
Package: libcurl4-gnutls-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 851
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: armhf
Multi-Arch: same
Source: curl
Version: 7.47.0-1ubuntu2
```


Will compile the 7.49 from source

**Comment by arybczak** [comment]
Symbol inflate is in zlib. What is the output of `curl-config --libs`? It should contain -lz.

**Comment by kowalcj0** [comment]
it doesn't containe `-lz` @arybczak 
`$ curl-config --libs
-L/usr/lib/arm-linux-gnueabihf -lcurl`

ps. omitting the `--with-curl` option when running `./configure.sh` didn't solve the issue

btw. here's the configuration I'd like to have
`./configure --with-curl --with-fftw --with-taglib --enable-outputs --enable-visualizer --enable-clock --enable-unicode`

**Comment by kowalcj0** [comment]
ps. what happened to last 2 or 3 comments?
they just disappeared!

ps. when I run `curl-config --libs` on my laptop there's also no `-lz`, but I've got no problems with building the project. Here's the output on my laptop
```
$ curl-config --libs
-L/usr/lib/x86_64-linux-gnu -lcurl
```

and here's from rpi 3:
```
$ curl-config --libs
-L/usr/lib/arm-linux-gnueabihf -lcurl
```

**Comment by kowalcj0** [comment]
strange, all the comments are visible again.

**Comment by kowalcj0** [comment]
is this issue somehow related to this https://curl.haxx.se/mail/lib-2016-04/0087.html ???

**Comment by arybczak** [comment]
Github was having some issues earlier, I guess that's the reason.

As for zlib, do you have it installed? Can you do `LDFLAGS="-lz" ./configure ...` and see if that fixes the problem?

**Comment by arybczak** [comment]
If all fails, you can compile without curl by passing `--without-curl` to configure.

**Comment by kowalcj0** [comment]
```bash
# I've reinstalled zlib
$ sudo apt-get install --reinstall zlibc zlib1g zlib1g-dev
Reading package lists... Done
Building dependency tree        
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apt-clone archdetect-deb dpkg-repack gir1.2-json-1.0 gir1.2-timezonemap-1.0 gir1.2-xkl-1.0 libdebian-installer4 libparted-fs-resize0 libtimezonemap-data libtimezonemap1 os-prober
  python3-icu python3-pam rdate
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  zlibc
0 upgraded, 1 newly installed, 2 reinstalled, 0 to remove and 7 not upgraded.
Need to get 107 kB/268 kB of archives.
After this operation, 206 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com xenial/main armhf zlib1g armhf 1:1.2.8.dfsg-2ubuntu4 [45,3 kB]
Get:2 http://ports.ubuntu.com xenial/universe armhf zlibc armhf 0.9k-4.3 [62,1 kB]
Fetched 107 kB in 0s (233 kB/s)
(Reading database ... 228574 files and directories currently installed.)
Preparing to unpack .../zlib1g_1%3a1.2.8.dfsg-2ubuntu4_armhf.deb ...
Unpacking zlib1g:armhf (1:1.2.8.dfsg-2ubuntu4) over (1:1.2.8.dfsg-2ubuntu4) ...
Setting up zlib1g:armhf (1:1.2.8.dfsg-2ubuntu4) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
(Reading database ... 228574 files and directories currently installed.)
Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-2ubuntu4_armhf.deb ...
Unpacking zlib1g-dev:armhf (1:1.2.8.dfsg-2ubuntu4) over (1:1.2.8.dfsg-2ubuntu4) ...
Selecting previously unselected package zlibc.
Preparing to unpack .../zlibc_0.9k-4.3_armhf.deb ...
Unpacking zlibc (0.9k-4.3) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for install-info (6.1.0.dfsg.1-5) ...
Setting up zlib1g-dev:armhf (1:1.2.8.dfsg-2ubuntu4) ...
Setting up zlibc (0.9k-4.3) ...

# then cleaned up the project
make clean

# configured it with `-lz` and curl
LDFLAGS="-lz" ./configure --with-curl --with-fftw --with-taglib --enable-outputs --enable-visualizer --enable-clock --enable-unicode
...
checking for curl-config... /usr/bin/curl-config
checking for curl_easy_init in -lcurl... yes
checking curl/curl.h usability... yes
checking curl/curl.h presence... yes
checking for curl/curl.h... yes
...

# then the build
make
...
mv -f .deps/window.Tpo .deps/window.Po
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++0x  -lz -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/lib/arm-linux-gnueabihf -lcurl -L/usr/local/lib -ltag
libtool: link: g++ -g -O2 -std=c++0x -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lz -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/lib/arm-linux-gnueabihf /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so -L/usr/local/lib -ltag -pthread
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so: undefined reference to symbol 'inflate'
/usr/lib/arm-linux-gnueabihf/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:534: recipe for target 'ncmpcpp' failed
make[2]: *** [ncmpcpp] Error 1
make[2]: Leaving directory '/home/rpi/git/ncmpcpp/src'
Makefile:467: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rpi/git/ncmpcpp'
Makefile:378: recipe for target 'all' failed
make: *** [all] Error 2
```


Then I tried compiling it without the cURL and it failed as well but with slightly different error:
```
make clean

./configure --without-curl --with-fftw --with-taglib --enable-outputs --enable-visualizer --enable-clock --enable-unicode

make
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++0x   -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/local/lib -ltag
libtool: link: g++ -g -O2 -std=c++0x -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/local/lib -ltag
/usr/local/lib/libtag.a(tzlib.cpp.o): In function `TagLib::zlib::decompress(TagLib::ByteVector const&)':
tzlib.cpp:(.text+0x2e): undefined reference to `inflateInit_'
tzlib.cpp:(.text+0xd2): undefined reference to `inflate'
tzlib.cpp:(.text+0xe4): undefined reference to `inflateEnd'
tzlib.cpp:(.text+0x11c): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status
Makefile:534: recipe for target 'ncmpcpp' failed
make[2]: *** [ncmpcpp] Error 1
make[2]: Leaving directory '/home/rpi/git/ncmpcpp/src'
Makefile:467: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rpi/git/ncmpcpp'
Makefile:378: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by kowalcj0** [comment]
I gave up and I've installed `ncmpcpp 0.7` from the official repo.

**Comment by kowalcj0** [comment]
I just tried installing `libghc-zlib-dev` but that didn't help.

```bash
sudo apt-get install libghc-zlib-dev
...
After this operation, 543 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
## damn 543 MB!!!!!!!!!!!!

make clean

LDFLAGS="-lz" ./configure --with-curl --with-fftw --with-taglib --enable-outputs --enable-visualizer --enable-clock --enable-unicode
# all went fine

# I've got the same error: 
make
...
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++0x  -lz -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/lib/arm-linux-gnueabihf -lcurl -L/usr/local/lib -ltag
libtool: link: g++ -g -O2 -std=c++0x -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lz -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/lib/arm-linux-gnueabihf /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so -L/usr/local/lib -ltag -pthread
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so: undefined reference to symbol 'inflate'
/usr/lib/arm-linux-gnueabihf/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:534: recipe for target 'ncmpcpp' failed
make[2]: *** [ncmpcpp] Error 1
make[2]: Leaving directory '/home/rpi/git/ncmpcpp/src'
Makefile:467: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rpi/git/ncmpcpp'
Makefile:378: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by arybczak** [comment]
What happens if you run `LIBS="-lz" ./configure ...` (LIBS instead of LDFLAGS)?

**Comment by kowalcj0** [comment]
same thing:

```
/bin/bash ../libtool  --tag=CXX   --mode=link g++  -g -O2 -std=c++0x   -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lz -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/lib/arm-linux-gnueabihf -lcurl -L/usr/local/lib -ltag
libtool: link: g++ -g -O2 -std=c++0x -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lz -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -L/usr/lib/arm-linux-gnueabihf /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so -L/usr/local/lib -ltag -pthread
/usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so: undefined reference to symbol 'inflate'
/usr/lib/arm-linux-gnueabihf/libz.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:534: recipe for target 'ncmpcpp' failed
make[2]: *** [ncmpcpp] Error 1
make[2]: Leaving directory '/home/rpi/git/ncmpcpp/src'
Makefile:467: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/rpi/git/ncmpcpp'
Makefile:378: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Corin-EU** [comment]
The difficulty with missing libraries when linking is not resolved just by appending the library to the list of libraries.  Order DOES matter.  The missing library which supplised the sysmbol (libz) has to be positioned before the library which uses the symbol libcutl-gnutls, eg

` -lz -L/usr/lib/arm-linux-gnueabihf /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so`

The problem is that configure uses curl-config which does not include -lz in its output string for "curl-config  --libs".

So one way get around this issue is to patch configure.ac to include "-lz" in the correct position.

See included patch -- multiple backquotes in code prevent showing code in markdown styling mode.
[configure.ac.patch.txt](https://github.com/arybczak/ncmpcpp/files/573507/configure.ac.patch.txt)

Once that patch is applied, then "autoreconf -fiv" must be invoked to rebuild "configure" as well as "aclocal.m4". It only "autogen.sh" is run, then on systems running a different libtool version (eg 2.4.2 on Debian stable/jessie) to that used to create the autoconf files being distributed (2.4.6) the result si that linking aborts with a libtool version mismatch error complaining about LT_INIT being the incorrect version value.

**Comment by Corin-EU** [comment]
OOPS!!!  My comment above  "The missing library (libz) which supplies the symbol (inflate) has to be positioned before the library (libcurl-gnutls) which uses the symbol" got the order the wrong way around.

According to the rules of linking order, libz must be placed after libcurl-gnutls ie request first, then supply.

On attempting the compilation on  i386 Linux Mint 18 (based Ubuntu 16.04) with gcc 5.4.0, linking failed after applying the patch with the same error about missing inflate.  On moving -lz to after -ltag, linking then works.

`g++ -O3 -fno-strict-aliasing -march=native -std=c++0x -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -lboost_thread -L/usr/local/lib /usr/local/lib/libmpdclient.so -lreadline -lpthread -lncursesw -ltinfo -lfftw3  -L/usr/lib/i386-linux-gnu /usr/lib/i386-linux-gnu/libcurl.so -ltag -lz  -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/lib/i386-linux-gnu -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/lib/i386-linux-gnu`

What I do not understand why the "-lz" before  libcurl.so works on Debian Jessie with gcc 4.9.  I cannot do a test on that system moving it to after, until tomorrow.  (I thought I had tried it after before submitting my solution and if had not worked.)

**Comment by Corin-EU** [comment]
Incidentally the ncmpcpp configure is using curl-config.  I thought that use of *-config scripts was considered deprecated and that PACKAGE CONFIG .pc files should always be used when available.

`
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/i386-linux-gnu
includedir=${prefix}/include
supported_protocols="DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS LDAP LDAPS POP3 POP3S RTMP RTSP SMB SMBS SMTP SMTPS TELNET TFTP"
supported_features="SSL IPv6 UnixSockets libz AsynchDNS IDN GSS-API SPNEGO Kerberos NTLM NTLM_WB TLS-SRP"

Name: libcurl
URL: http://curl.haxx.se/
Description: Library to transfer files with ftp, http, etc.
Version: 7.47.0
Libs: -L${libdir} -lcurl
Libs.private: -lidn -lrtmp -lssl -lcrypto -lssl -lcrypto -L/usr/lib/i386-linux-gnu/mit-krb5 -Wl,-Bsymbolic-functions -Wl,-z,relro -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -llber -lldap -lz
Cflags: -I${includedir} 
`

**Comment by arybczak** [comment]
> The source of the problem appears to be that configure uses "curl-config" which does not include "-lz" in its output string for "curl-config --libs".

Mine does - it appears it's a bug in curl.

>  I thought that use of *-config scripts was considered deprecated

I don't know anything about that.

**Comment by Corin-EU** [comment]
I have now tested build ncmpcpp on Debian Jessie on armhf with the patch to add "-lz" after "ltags" (where it should be according to the rules) and it does build successfully with that.

`--- configure.ac.orig  2016-10-31 12:24:35.000000000 +0100
+++ configure.ac        2016-10-31 12:24:35.000000000 +0100
@@ -342,5 +342,7 @@
        fi
 fi
 
+LIBS="$LIBS -lz"
+
 AC_CONFIG_FILES([Makefile src/Makefile doc/Makefile])
 AC_OUTPUT`

[configure.ac.patch.txt](https://github.com/arybczak/ncmpcpp/files/573976/configure.ac.patch.txt)

The reason why using the LIBS="-lz" environmental variable does not work is because its contents are prepended to the lists of libraries to be linked against, which of course does not work.

So using this patch on both Linux Mint 18 (based on Ubunt 16.04) and Debian 8.6 Jessie results in no "missing  inflate" symbol and a successful build.

Incidentally it is also necessary to also build one's own copy of libtag (1.11.1 now available) (and the dependent libtag-extras  if desired) because linking against the libtag supplied by Linux Mint 18 and Debian 8.6 Jessies results in numerous undefined errors mentioned in another issue.


As for "I don't know anything about that.", if you read articles such as  "Best practices with autotools" dated August 23, 2005, they mention the use of pkg-config (which consults the pc files) and most software distritbutions providedd a pkg-config file now rather than a {sofware}-config shell script.

For a HOWTO use guide on pkg-config see

<https://people.freedesktop.ORG/~dbn/pkg-config-guide.html>

**Comment by arybczak** [comment]
configure.ac now uses pkgconfig for libcurl.

**Comment by Corin-EU** [comment]
Thank you for updating configure.ac to now use pkgconfig for libcurl (and hopefully other {software}-config shell script instances as well, but the latest Git revision r.ba83b9d still fails to build on Linux Mint 18/Ubuntu 16.04 and Debian Jessie 8.5 with the same error

`info -lfftw3 -lcurl -L/usr/local/lib -ltag
libtool: link: g++ -O3 -fno-strict-aliasing -march=native -std=c++14 -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lz -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -L/usr/local/lib /usr/local/lib/libmpdclient.so -lreadline -lpthread -lncursesw -ltinfo -lfftw3 /usr/lib/i386-linux-gnu/libcurl.so -ltag -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/lib/i386-linux-gnu -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/lib/i386-linux-gnu
/usr/bin/ld: /usr/lib/i386-linux-gnu/libcurl.so: undefined reference to symbol 'inflate'
/usr/lib/i386-linux-gnu/libz.so: error adding symbols: DSO missing from command line
`

The patch supplied above

https://github.com/arybczak/ncmpcpp/files/573976/configure.ac.patch.txt

still needs to be applied for successful building

`/bin/sh ../libtool  --tag=CXX   --mode=link g++  -O3 -fno-strict-aliasing -march=native -std=c++14   -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lz -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -L/usr/local/lib -lmpdclient -lreadline -lpthread -lncursesw -ltinfo -lfftw3 -lcurl -L/usr/local/lib -ltag -lz
libtool: link: g++ -O3 -fno-strict-aliasing -march=native -std=c++14 -o ncmpcpp comparators.o html.o option_parser.o string.o type_conversions.o wide_string.o actions.o bindings.o browser.o charset.o clock.o configuration.o curl_handle.o display.o enums.o format.o global.o help.o helpers.o lastfm.o lastfm_service.o lyrics.o lyrics_fetcher.o macro_utilities.o media_library.o mpdpp.o mutable_song.o ncmpcpp.o outputs.o playlist.o playlist_editor.o screen.o screen_type.o scrollpad.o search_engine.o sel_items_adder.o server_info.o settings.o song.o song_info.o song_list.o sort_playlist.o status.o statusbar.o tag_editor.o tags.o tiny_tag_editor.o title.o visualizer.o window.o  -lboost_filesystem -lboost_system -lboost_locale -lboost_program_options -lboost_regex -licuuc -licudata -L/usr/local/lib /usr/local/lib/libmpdclient.so -lreadline -lpthread -lncursesw -ltinfo -lfftw3 /usr/lib/i386-linux-gnu/libcurl.so -ltag -lz -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/lib/i386-linux-gnu -Wl,-rpath -Wl,/usr/local/lib -Wl,-rpath -Wl,/usr/lib/i386-linux-gnu
make[2]: Leaving directory '/srv/repository/git/ncmpcpp/src'`

You no doubt want to keep this issue closed, but after nearly 5 months since the original post, you have actually applied a fix, unless you consider that the solution is people should switch from Debian Jessie and Linux Mint18/Ubuntu 16.04 to another distribution which has a properly built libcurl.

**Comment by arybczak** [comment]
I am not going to apply this patch as-is, but if you could write it so, after checking for curl, configure will try to link a program that uses libcurl and if that fails, try again with -lz added to LIBS and if that succeeds, then adds -lz to LIBS?
