### PR TITLE
Return now playing command

### PR DESCRIPTION
**Pull request by vaygr**
Hi,

we discussed this about a week ago in PM, and finally I got some time yesterday to code.

I find such functionality quite essential for every audio player (modular or not, mpd-oriented or not), since it is the only way external applications can get song information from the player inside an operating system. Some write files (like Audacious, Sonata), others (deadbeef) -- provide switches to display information for a currently playing track. It is useful in cases when you want to use such information in IM (like an IRC/Jabber client), and some people even mentioned it on boards. Of course for super-scripting cases (for example on a server) I would use mpc and its powerful commandline, but for a desktop I do not need 2 players for such simple tasks, really.

This one adds configure switches to enable/disable the feature and reuses some code block from the main loop in ncmpcpp.cpp. It displays currently playing song according to song_status_format value defined in the config.

Note, it is just the 1st draft, so comments and corrections are welcome.

At the moment, as you may have noticed, it's for 0.6.x branch (which, by the way has default config stating '--now-playing' switch while it doesn't exist), because master has too many compilation errors with GCC 4.6. I'll work on it once I switch my boxes to 4.9 or even 5.1 (I suppose 0.7 will be released by that time).

Thanks!

### CODE REVIEW

**Comment by arybczak** [comment]
Implemented in git under --current-song. I brought it back because it may be argued that this function differs from mpc's one because of different song formats as one may not want to learn mpc formatting and reuse ncmpcpp's one instead.

**Comment by vaygr** [comment]
Thanks!
